In [4]:
import torch

In [5]:
x= torch.empty(1,2) #2d
x

tensor([[2.2179e+12, 4.4773e-41]])

In [7]:
x= torch.empty(2,2,3)  #3d
x

tensor([[[-1.5458e-27,  3.1270e-41, -4.9511e-27],
         [ 3.1270e-41,  2.1286e+12,  1.9618e-44]],

        [[ 5.5219e+03, -6.7513e-07,  2.1286e+12],
         [ 4.4773e-41, -5.2717e+12,  3.8582e+16]]])

In [9]:
x= torch.rand(3,2)
x

tensor([[0.4137, 0.6332],
        [0.8558, 0.8317],
        [0.4024, 0.6879]])

In [11]:
x= torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
x.dtype

torch.float32

In [13]:
x= torch.zeros(2,3, dtype=torch.int)
x

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [15]:
x= torch.zeros(2,3, dtype=torch.float16)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [17]:
x.size()

torch.Size([2, 3])

In [19]:
x = torch.rand(2,3)
y = torch.rand(2,3)
print(x)
print(y)

tensor([[0.9921, 0.6728, 0.8823],
        [0.9363, 0.3306, 0.5893]])
tensor([[0.5764, 0.0849, 0.8348],
        [0.9983, 0.9402, 0.5342]])


In [20]:
z = x.add_(y)
z

tensor([[1.5686, 0.7577, 1.7171],
        [1.9347, 1.2707, 1.1235]])

In [22]:
print(x)
print(y)

tensor([[1.5686, 0.7577, 1.7171],
        [1.9347, 1.2707, 1.1235]])
tensor([[2.1450, 0.8426, 2.5519],
        [2.9330, 2.2109, 1.6578]])


In [21]:
y.add_(x)

tensor([[2.1450, 0.8426, 2.5519],
        [2.9330, 2.2109, 1.6578]])

In [23]:
z = x-y
z = torch.sub(x,y)
z

tensor([[-0.5764, -0.0849, -0.8348],
        [-0.9983, -0.9402, -0.5342]])

In [24]:
print(x)
print(y)

tensor([[1.5686, 0.7577, 1.7171],
        [1.9347, 1.2707, 1.1235]])
tensor([[2.1450, 0.8426, 2.5519],
        [2.9330, 2.2109, 1.6578]])


In [25]:
z = x*y
z = torch.mul(x,y)
z

tensor([[3.3645, 0.6385, 4.3819],
        [5.6743, 2.8095, 1.8625]])

In [27]:
x = torch.rand(5,4)
x

tensor([[0.4921, 0.2743, 0.5312, 0.2637],
        [0.0638, 0.2144, 0.6055, 0.5223],
        [0.6879, 0.9372, 0.6655, 0.1715],
        [0.8151, 0.0305, 0.2343, 0.6648],
        [0.0729, 0.1244, 0.5113, 0.4366]])

In [29]:
x[:, 1]

tensor([0.2743, 0.2144, 0.9372, 0.0305, 0.1244])

In [30]:
x[:, 1:2]

tensor([[0.2743],
        [0.2144],
        [0.9372],
        [0.0305],
        [0.1244]])

In [31]:
x[:, 1:3]

tensor([[0.2743, 0.5312],
        [0.2144, 0.6055],
        [0.9372, 0.6655],
        [0.0305, 0.2343],
        [0.1244, 0.5113]])

In [34]:
x[4, :]

tensor([0.0729, 0.1244, 0.5113, 0.4366])

In [ ]:
#

In [35]:
import numpy as np

In [37]:
a= torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [38]:
b =a.numpy()
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
# tensor on cpu not gpu both objacts same location

In [39]:
a.add_(1)
print(a)
print(b)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [43]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
b

[1. 1. 1. 1. 1.]


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [44]:
a += 2
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [45]:
# GPU

In [46]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(6)
  y = y.to(device)
  z = x + y
  z = z.to('cpu')

In [2]:
import torch
print("cuda") if torch.cuda.is_available() else print('_cpu')

cuda


In [3]:
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)