In [2]:
import torch

In [4]:
x = torch.rand(5, requires_grad=True)
x

tensor([0.8755, 0.6907, 0.5553, 0.2138, 0.2917], requires_grad=True)

In [ ]:
# calculate some gradient

In [5]:
y= x + 2
y # grad_fn=<AddBackward0

tensor([2.8755, 2.6907, 2.5553, 2.2138, 2.2917], grad_fn=<AddBackward0>)

In [6]:
z = y*y*2
z # grad_fn=<MulBackward

tensor([16.5370, 14.4797, 13.0588,  9.8016, 10.5035], grad_fn=<MulBackward0>)

In [7]:
z = z.mean()
z # grad_fn=<MeanBackward

tensor(12.8761, grad_fn=<MeanBackward0>)

In [ ]:
# calculate grad

In [8]:
z.backward()
print(x.grad)

tensor([2.3004, 2.1526, 2.0442, 1.7710, 1.8333])


# Preventing Gardient history

In [ ]:
## In pytorch trailing _ meaning this function is modified varibale inplace

In [3]:
x = torch.randn(3, requires_grad=True)
print(x)

# x.requires_grad_(False)
# x.detach()     # creating new tensor donesnt requires the gradient
# with torch.no_grad():

with torch.no_grad():
  y = x+2
  print(y) # o/p = doesnt show gradient fun attribute


tensor([-1.2216, -0.4624, -0.0386], requires_grad=True)
tensor([0.7784, 1.5376, 1.9614])


# Training Example

In [7]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)


tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])


In [8]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
# optimozers used

In [ ]:
# optimizer
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()


In [2]:
!pip install youtube-transcript-api

In [14]:
from youtube_transcript_api import YouTubeTranscriptApi

YouTubeTranscriptApi.get_transcript('UQBlRjNW74g', languages='mr')

TranscriptsDisabled: ignored

In [16]:
import requests
from bs4 import BeautifulSoup

# Replace 'URL' with the URL of the webpage you want to scrape
url = 'https://vivekpatait.blogspot.com/'

# Send a GET request to the URL
response = requests.get(url)

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

# Find and extract Marathi text (example for paragraph tags <p>)
marathi_text = []
for paragraph in soup.find_all('p'):
    if paragraph.get_text():  # Check if the paragraph has text content
        marathi_text.append(paragraph.get_text())

# Print the extracted Marathi text
for text in marathi_text:
    print(text)


Marathi stories, kavita
स्वामी त्रिकालदर्शी आपल्या गुहेत ध्यानस्थ बसले होते. २५ वर्षाचे युवा व्यापारी धर्मदेव स्वामींच्या दर्शनार्थ आले. आपली समस्या स्वामींच्या पुढे मांडत धर्मदेव म्हणाले, माझ्या वडिलांचा मृत्यू असमय झाला. त्यांची इच्छा व्यापारातून मिळालेल्या फायद्याचा अधिकांश भाग समाजसेवेसाठी खर्च करायची होती. पण गेल्या काही वर्षांपासून व्यापारात सतत तोटा होत असल्याने, ईच्छा असूनही ते समाजसेवा करू शकले नाही. वडिलांच्या मृत्यू  समयी  त्यांच्या समस्त इच्छा पूर्ण करण्याचे मी वचन दिले आहे. त्यांच्या एवढ्या इच्छा कश्या पूर्ण करू हेच मला कळत नाही. स्वामीजी धर्मदेव कडे पहात  हसत-हसत म्हणाले, त्यांच्या सर्व इच्छा तू सहज पूर्ण करू शकतो. स्वामीजींनी धर्मदेवला एक कान मंत्र दिला.
पुढील २० वर्षांत धर्मदेव यांनी वडिलांच्या स्मृतीत अनेक शाळा, कॉलेजेस अनाथाश्रम, वृध्दाश्रम बांधले. एक मोठे चॅरीटेबल हॉस्पिटल ही बांधले. कोट्यवधी  रुपये दरवर्षी ते यासाठी खर्च करतात. एकदा एका पत्रकाराने त्यांना याबाबत प्रश्न विचारला, तुम्ही कोणताही व्यापार, धंधा,  उद्योग करत नाही, मग हे सर्व तुम्हाला कसे काय जमते. धर्मदेव